### GET TEST
GET localhost:880/iitp/api/sensor?id=1

### POST TEST
POST localhost:880/iitp/api/sensor
Content-Type: application/json

{
"ID": 1,
"batt": 3.7,
"magx": 6687.0,
"MAGy": 3047.0,
"MAGz": 2673.0,
"ZYROx": 4063.0,
"ZYROy": 62864.0,
"ZYROz": 1043.0,
"ACCx": 65138.0,
"ACCy": 29.0,
"ACCz": 1874.0,
"AQI": 1.0,
"TVOC": 16.0,
"EC2": 400,
"PM1.0": 1,
"PM2.5": 2,
"pm10": 3,
"IRUN": 19225.0,
"RED": 17433.0,
"ECG": 30241.0,
"TEMP": 27.5
}