### GET TEST
GET localhost:880/iitp/data?id=1

### POST TEST
POST localhost:880/iitp/data
Content-Type: application/json

{
  "ID": 1,
  "batt": 1.1,
  "MAG_X": 2,
  "MAG_Y": 3,
  "MAG_Z": 4,
  "ZYRO_X": 5,
  "ZYRO_Y": 6,
  "ZYRO_Z": 7,
  "ACC_X": 8,
  "ACC_Y": 9,
  "ACC_Z": 10,
  "AQI": 11,
  "TVOC": 12,
  "ECO2": 13,
  "PM_10": 14,
  "PM_25": 15,
  "PM_100": 16,
  "IRUN": 17,
  "RED": 18,
  "ECG": 19,
  "TEMP": 20
}

### POST TEST2
POST localhost:880/iitp/data
Content-Type: application/json

{
"ID": 2,
"batt": 3.7,
"magx": 6687.0,
"MAGy": 3047.0,
"MAGz": 2673.0,
"ZYROx": 4063.0,
"ZYROy": 62864.0,
"ZYROz": 1043.0,
"ACCx": 65138.0,
"ACCy": 29.0,
"ACCz": 1874.0,
"AQI": 1.0,
"TVOC": 16.0,
"EC2": 400,
"pm1.0": 0,
"pm2.5": 0,
"pm10": 0,
"IRUN": 19225.0,
"RED": 17433.0,
"ECG": 30241.0,
"TEMP": 27.5
}